.pragma library

// Turns a kawt theme ({ bg, fg, dim, border, accent, warn }) into a 16-color terminal palette
// and config snippets for other programs. Pure functions, no QML.

const names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];
// Two looks for the terminal colors, picked in the style panel:
//   soft: muted, the ink ramp goes deep into the dim end
//   crt:  bright and crisp, like an old monochrome monitor turned up
// Each entry: green yellow blue magenta cyan as [real hue, brightness on the dim -> fg ramp,
// how much of the real hue shows]. Red is always the theme's own `warn`.
const styles = {
    soft: {
        inks: [["#7cb36b", 1.0, 0.22], ["#d9b45b", 0.85, 0.28], ["#6a93d4", 0.62, 0.2], ["#b07ad1", 0.72, 0.2], ["#5fb2b0", 0.5, 0.2]],
        comment: 0 // color8: how far from dim toward fg
    },
    crt: {
        inks: [["#7cb36b", 1.0, 0.22], ["#d9b45b", 0.92, 0.28], ["#6a93d4", 0.8, 0.22], ["#b07ad1", 0.86, 0.22], ["#5fb2b0", 0.74, 0.22]],
        comment: 0.3
    }
};
const styleNames = Object.keys(styles);

function rgb(h) {
    return [1, 3, 5].map(i => parseInt(h.slice(i, i + 2), 16));
}

function mix(a, b, t) {
    const x = rgb(a), y = rgb(b);
    return "#" + x.map((v, i) => Math.round(v + (y[i] - v) * t).toString(16).padStart(2, "0")).join("");
}

function isLight(t) {
    const [r, g, b] = rgb(t.bg);
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.5;
}

// color0..15, like an old monochrome monitor: every color is the theme's own ink at a
// different brightness (dim -> fg), with just a hint of the real hue so ls/git/diff stay
// readable. Amber stays amber, phosphor stays green, mono stays gray; only red is red.
function ansi(t, style) {
    const st = styles[style] || styles.crt;
    const light = isLight(t);
    const normal = [t.warn, ...st.inks.map(([hue, level, tint]) => mix(mix(t.dim, t.fg, level), hue, tint))];
    const bright = normal.map(c => mix(c, t.fg, 0.4));
    const comment = mix(t.dim, t.fg, st.comment);
    // color0 ("black") is still used as a text color by some programs, so it must stay
    // visible on the background instead of nearly matching it
    const black = mix(t.bg, t.fg, light ? 0.48 : 0.38);
    // Light: swap the roles (like PaperColor), since programs print "white" text assuming a
    // dark terminal. "white" becomes dark ink, "black" a light gray, so everything stays readable.
    if (light)
        return [black, ...normal, mix(t.fg, t.bg, style === "soft" ? 0.25 : 0.15), comment, ...bright, t.fg];
    return [black, ...normal, mix(t.fg, t.bg, style === "soft" ? 0.2 : 0.12), comment, ...bright, t.fg];
}

// color16..255: the xterm cube and gray ramp, recolored the same way. Programs that use the
// 256-color palette (powerlevel10k, eza, bat, btop...) would otherwise show xterm's own bright
// blues and pure white, which is what clashed with the theme. Each color keeps its brightness
// (dark stays dark, light stays light, so it still reads) but becomes the theme's ink, with a
// hint of the original hue. On light themes brightness flips, like the 16 colors do.
function extended(t, style) {
    const tint = style === "soft" ? 0.15 : 0.22;
    const light = isLight(t);
    const cube = [0, 95, 135, 175, 215, 255];
    const out = [];
    for (let i = 16; i < 256; i++) {
        let r, g, b;
        if (i < 232) {
            const n = i - 16;
            [r, g, b] = [cube[Math.floor(n / 36)], cube[Math.floor(n / 6) % 6], cube[n % 6]];
        } else {
            r = g = b = 8 + (i - 232) * 10;
        }
        const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
        // never come close to the background: even the darkest color is used as text somewhere
        const ink = mix(t.bg, t.fg, 0.4 + 0.6 * lum);
        const hex = "#" + [r, g, b].map(v => v.toString(16).padStart(2, "0")).join("");
        out.push(r === g && g === b ? ink : mix(ink, hex, tint * (light ? 0.8 : 1)));
    }
    return out;
}

function rgba(c, alpha) {
    return `rgba(${c.slice(1)}${alpha || "ff"})`;
}

// file name -> content
function files(name, t, style) {
    const a = ansi(t, style);
    const x = extended(t, style);
    const head = `kawt theme: ${name} (generated by kawt-shell, overwritten on theme change)`;
    const bare = c => c.slice(1);

    return {
        "colors.json": JSON.stringify(Object.assign({ name }, t, { ansi: a }), null, 2),

        "colors.sh": [
            `# ${head}`,
            "# usage: . ~/.local/state/kawt/theme/colors.sh",
            `KAWT_THEME=${name}`,
            ...["bg", "fg", "dim", "border", "accent", "warn"].map(k => `KAWT_${k.toUpperCase()}='${t[k]}'`),
            ...a.map((c, i) => `KAWT_COLOR${i}='${c}'`)
        ].join("\n"),

        "kitty.conf": [
            `# ${head}`,
            "# kitty.conf: include ~/.local/state/kawt/theme/kitty.conf",
            `foreground ${t.fg}`,
            `background ${t.bg}`,
            `cursor ${t.accent}`,
            `cursor_text_color ${t.bg}`,
            `selection_foreground ${t.bg}`,
            `selection_background ${t.accent}`,
            `url_color ${t.accent}`,
            `active_border_color ${t.accent}`,
            `inactive_border_color ${t.border}`,
            `tab_bar_background ${t.bg}`,
            `active_tab_foreground ${t.accent}`,
            `active_tab_background ${t.bg}`,
            `inactive_tab_foreground ${t.dim}`,
            `inactive_tab_background ${t.bg}`,
            ...a.map((c, i) => `color${i} ${c}`),
            ...x.map((c, i) => `color${i + 16} ${c}`)
        ].join("\n"),

        "foot.ini": [
            `# ${head}`,
            "# foot.ini: include=~/.local/state/kawt/theme/foot.ini",
            "[colors]",
            `foreground=${bare(t.fg)}`,
            `background=${bare(t.bg)}`,
            `selection-foreground=${bare(t.bg)}`,
            `selection-background=${bare(t.accent)}`,
            ...a.slice(0, 8).map((c, i) => `regular${i}=${bare(c)}`),
            ...a.slice(8).map((c, i) => `bright${i}=${bare(c)}`),
            ...x.map((c, i) => `${i + 16}=${bare(c)}`)
        ].join("\n"),

        "alacritty.toml": [
            `# ${head}`,
            '# alacritty.toml: [general] import = ["~/.local/state/kawt/theme/alacritty.toml"]',
            "[colors.primary]",
            `background = "${t.bg}"`,
            `foreground = "${t.fg}"`,
            "",
            "[colors.cursor]",
            `cursor = "${t.accent}"`,
            `text = "${t.bg}"`,
            "",
            "[colors.normal]",
            ...names.map((n, i) => `${n} = "${a[i]}"`),
            "",
            "[colors.bright]",
            ...names.map((n, i) => `${n} = "${a[i + 8]}"`),
            "",
            "[colors]",
            `indexed_colors = [${x.map((c, i) => `{ index = ${i + 16}, color = "${c}" }`).join(", ")}]`
        ].join("\n"),

        // a table, for hyprland.lua: local colors = dofile(".../hyprland_colors.lua")
        "hyprland_colors.lua": [
            `-- ${head}`,
            "return {",
            `    m_active = "${rgba(t.accent, "ee")}",`,
            `    m_inactive = "${rgba(t.border, "aa")}",`,
            `    m_shadow = "${rgba("#000000", isLight(t) ? "22" : "44")}",`,
            "}"
        ].join("\n"),

        "hyprland.conf": [
            `# ${head}`,
            "# hyprland.conf: source = ~/.local/state/kawt/theme/hyprland.conf",
            "general {",
            `    col.active_border = ${rgba(t.accent)}`,
            `    col.inactive_border = ${rgba(t.border)}`,
            "}"
        ].join("\n")
    };
}

// OSC escape sequences that recolor a running terminal (the pywal trick)
function sequences(t, style) {
    const osc = (code, c) => `\x1b]${code};${c}\x1b\\`;
    return [...ansi(t, style), ...extended(t, style)].map((c, i) => osc(`4;${i}`, c)).join("")
        + osc(10, t.fg) + osc(11, t.bg) + osc(12, t.accent) + osc(17, t.accent) + osc(19, t.bg);
}
