.pragma library

// Turns a kawt theme ({ bg, fg, dim, border, accent, warn }) into a 16-color terminal palette
// and config snippets for other programs. Pure functions, no QML.

const names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];
// green yellow blue magenta cyan; red comes from the theme's own `warn`
const hues = ["#7cb36b", "#d9b45b", "#6a93d4", "#b07ad1", "#5fb2b0"];

function rgb(h) {
    return [1, 3, 5].map(i => parseInt(h.slice(i, i + 2), 16));
}

function mix(a, b, t) {
    const x = rgb(a), y = rgb(b);
    return "#" + x.map((v, i) => Math.round(v + (y[i] - v) * t).toString(16).padStart(2, "0")).join("");
}

function isLight(t) {
    const [r, g, b] = rgb(t.bg);
    return (0.299 * r + 0.587 * g + 0.114 * b) / 255 > 0.5;
}

// color0..15. Hues are pulled toward the theme's text color so each theme keeps its tint
// (phosphor stays greenish, amber warm, mono gray).
function ansi(t) {
    const light = isLight(t);
    const normal = [t.warn, ...hues.map(h => mix(h, t.fg, light ? 0.5 : 0.35))];
    const bright = normal.map(c => mix(c, light ? "#000000" : "#ffffff", 0.2));
    // (bright black, color8, is used for comments/hints, so it stays mid-gray in both)
    // Light: swap the roles (like PaperColor), since programs print "white" text assuming a
    // dark terminal. "white" becomes dark ink, "black" a light gray, so everything stays readable.
    if (light)
        return [t.hoverFill, ...normal, mix(t.fg, t.bg, 0.25), t.dim, ...bright, t.fg];
    return [t.border, ...normal, mix(t.fg, t.bg, 0.2), t.dim, ...bright, t.fg];
}

function rgba(c, alpha) {
    return `rgba(${c.slice(1)}${alpha || "ff"})`;
}

// file name -> content
function files(name, t) {
    const a = ansi(t);
    const head = `kawt theme: ${name} (generated by kawt-shell, overwritten on theme change)`;
    const bare = c => c.slice(1);

    return {
        "colors.json": JSON.stringify(Object.assign({ name }, t, { ansi: a }), null, 2),

        "colors.sh": [
            `# ${head}`,
            "# usage: . ~/.local/state/kawt/theme/colors.sh",
            `KAWT_THEME=${name}`,
            ...["bg", "fg", "dim", "border", "accent", "warn"].map(k => `KAWT_${k.toUpperCase()}='${t[k]}'`),
            ...a.map((c, i) => `KAWT_COLOR${i}='${c}'`)
        ].join("\n"),

        "kitty.conf": [
            `# ${head}`,
            "# kitty.conf: include ~/.local/state/kawt/theme/kitty.conf",
            `foreground ${t.fg}`,
            `background ${t.bg}`,
            `cursor ${t.accent}`,
            `cursor_text_color ${t.bg}`,
            `selection_foreground ${t.bg}`,
            `selection_background ${t.accent}`,
            `url_color ${t.accent}`,
            `active_border_color ${t.accent}`,
            `inactive_border_color ${t.border}`,
            `tab_bar_background ${t.bg}`,
            `active_tab_foreground ${t.accent}`,
            `active_tab_background ${t.bg}`,
            `inactive_tab_foreground ${t.dim}`,
            `inactive_tab_background ${t.bg}`,
            ...a.map((c, i) => `color${i} ${c}`)
        ].join("\n"),

        "foot.ini": [
            `# ${head}`,
            "# foot.ini: include=~/.local/state/kawt/theme/foot.ini",
            "[colors]",
            `foreground=${bare(t.fg)}`,
            `background=${bare(t.bg)}`,
            `selection-foreground=${bare(t.bg)}`,
            `selection-background=${bare(t.accent)}`,
            ...a.slice(0, 8).map((c, i) => `regular${i}=${bare(c)}`),
            ...a.slice(8).map((c, i) => `bright${i}=${bare(c)}`)
        ].join("\n"),

        "alacritty.toml": [
            `# ${head}`,
            '# alacritty.toml: [general] import = ["~/.local/state/kawt/theme/alacritty.toml"]',
            "[colors.primary]",
            `background = "${t.bg}"`,
            `foreground = "${t.fg}"`,
            "",
            "[colors.cursor]",
            `cursor = "${t.accent}"`,
            `text = "${t.bg}"`,
            "",
            "[colors.normal]",
            ...names.map((n, i) => `${n} = "${a[i]}"`),
            "",
            "[colors.bright]",
            ...names.map((n, i) => `${n} = "${a[i + 8]}"`)
        ].join("\n"),

        // a table, for hyprland.lua: local colors = dofile(".../hyprland_colors.lua")
        "hyprland_colors.lua": [
            `-- ${head}`,
            "return {",
            `    m_active = "${rgba(t.accent, "ee")}",`,
            `    m_inactive = "${rgba(t.border, "aa")}",`,
            `    m_shadow = "${rgba("#000000", isLight(t) ? "22" : "44")}",`,
            "}"
        ].join("\n"),

        "hyprland.conf": [
            `# ${head}`,
            "# hyprland.conf: source = ~/.local/state/kawt/theme/hyprland.conf",
            "general {",
            `    col.active_border = ${rgba(t.accent)}`,
            `    col.inactive_border = ${rgba(t.border)}`,
            "}"
        ].join("\n")
    };
}

// OSC escape sequences that recolor a running terminal (the pywal trick)
function sequences(t) {
    const osc = (code, c) => `\x1b]${code};${c}\x1b\\`;
    return ansi(t).map((c, i) => osc(`4;${i}`, c)).join("")
        + osc(10, t.fg) + osc(11, t.bg) + osc(12, t.accent) + osc(17, t.accent) + osc(19, t.bg);
}
